app.user.storage.path=./users.json
smtp.host=smtp.example.com
smtp.port=587
smtp.username=user@example.com
smtp.password=your_password
smtp.ssl.enabled=true
app.default.locale=ru_RU
security.min.password.length=6
security.min.login.length=3
logging.level.org.malenikajkat=INFO
server.port=8080